### ISSUE TITLE
Adding something to a farm area

### ISSUE THREAD

**Issue by thedude459** [farmOS-legacy/farm_area#2]
I am not sure if this is the correct repo to add this enhancement to but is it possible to have geometry automatically go to the area you are adding information for when adding activity, input, observation, soil test or movement?

For the logging of anything it would be nice if the area was a dropdown of all areas that have been added.  I think having as many fields as dropdown as there can be would be very helpful.

On the soil test, would it be beneficial to break this down into fields for the test?  For instance Umass Amherst soil test has:
Includes pH, acidity, Modified Morgan extractable nutrients
(P, K, Ca, Mg, Fe, Mn, Zn, Cu, B), lead, and aluminum,
cation exchange capacity, and percent base saturation

Then change the notes field into recommendations.

This way you could chart the change for a certain nutrient over a defined length of time from a reporting standpoint.  The nutrient levels could also we tied to how well the crop did.

**Comment by mstenta** [comment]
@thedude459 Hi Matt! Sorry it took me a while to respond to this... I gave a farmOS workshop at the NOFA Summer Conference this past weekend and needed to prepare for it.

To answer your questions:

> is it possible to have geometry automatically go to the area you are adding information for when adding activity, input, observation, soil test or movement?

Yes this already happens!  (If I understand you correctly)  Right now, if you create an "Activity" (for example), and specify that it happened in "North field", and the "North field" area has a geometry associated with it, that geometry will automatically be copied to the Activity log's geometry field when you save it... UNLESS you add your own geometry to the activity first.  Basically the logic is: when a log is saved, if it doesn't have a geometry, but it does have an area reference, then copy the geometry of that area to the log.  Is that what you meant?

Or... do you mean: "When I add an activity, and I draw a geometry for that activity, automatically look up what Area(s) that geometry overlaps with and use that to auto-fill the "Areas" reference field on the activity?

That's a bit trickier - but a great idea regardless!  I created a new feature request in the Farm Log module queue: https://www.drupal.org/node/2784899

> For the logging of anything it would be nice if the area was a dropdown of all areas that have been added. I think having as many fields as dropdown as there can be would be very helpful.

I agree! This would not be a difficult change to make.  When I originally created the area reference fields, I decided to make them use Drupal's "Autocomplete (free tagging)" widget type - because it allowed you to EITHER select an existing area, OR create a new one, all with the same field.  This is convenient, but I think in most cases people will (and maybe should) create their areas ahead of time, and then reference them from the logs - so the ability to create new areas on-the-fly may not be necessary (or advisable).  We could make this change quite simply by changing the widget to a dropdown, which is an option provided by Drupal core already.

New feature request: https://www.drupal.org/node/2784901

> On the soil test, would it be beneficial to break this down into fields for the test? For instance Umass Amherst soil test has:
> Includes pH, acidity, Modified Morgan extractable nutrients (P, K, Ca, Mg, Fe, Mn, Zn, Cu, B), lead, and aluminum, cation exchange capacity, and percent base saturation

Yes that is ultimately where I see the Soil Test log type heading.  The first pass at it was quite simple, but adding additional fields for specific measurements is a logical next step.  Adding the fields is easy.  The biggest challenge is on the farmers: they would need to manually input all the data points.  But, perhaps in the future, if farmOS gains traction, soil labs can create their own farmOS integration modules that automatically push data to a farmer's farmOS, and auto-fill those fields.  This is something I am hoping to explore with my work at the Cornell Soil Health lab. Hopefully it can provide an example that other labs can follow.

Let's use this feature request to discuss what fields we should add in the first pass: https://www.drupal.org/node/2784911

> Then change the notes field into recommendations.

The "Notes" field is common to all log types, so I don't think we should change it.  But perhaps adding another one specifically for soil improvement recommendations would be a good idea.

All great ideas!  Keep them coming!  And don't worry about which issue queue they belong in - I'll move things around as necessary.  I don't expect everyone to know the full relationship between modules yet - but I'll try to get some better documentation on that going too!

**Comment by mstenta** [comment]
Closing this - we can focus discussion on the specific features in each of their own nodes on drupal.org.
